//
// This file was generated by the Retargetable Decompiler
// Website: https://retdec.com
// Copyright (c) 2017 Retargetable Decompiler <info@retdec.com>
//

#include <stdint.h>
#include <stdio.h>

// ------------------------ Functions -------------------------

// Address range: 0x80483fb - 0x80484af
int main(int argc, char ** argv) {
    // 0x80483fb
    putchar(65);
    putchar(105);
    putchar(110);
    putchar(39);
    putchar(116);
    putchar(32);
    putchar(72);
    putchar(101);
    putchar(114);
    putchar(101);
    putchar(10);
    return 0;
}

// --------------- Dynamically Linked Functions ---------------

// int putchar(int c);

// --------------------- Meta-Information ---------------------

// Detected compiler/packer: gcc (4.9.2)
// Detected functions: 1
// Decompiler release: v2.2.1 (2016-09-07)
// Decompilation date: 2017-04-01 13:33:04
